# Benchmark last visit
This python notebook trains, tests and evaluates the benchmark last visit. In the first piece of code, testing is done on a longitudinal data set (D2) and in the second piece of code, tesing is done on a cross-sectional data set (D3).
Data set used for training and evalution are D1_D2 and D4 ADNI data sets respectively.

Train model on data set D1_D2 and test model on longitudinal data set D2

In [2]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import BenchmarkLastVisit
from tadpole_algorithms.preprocessing.split import split_test_train_tadpole

"""
Train model on ADNI data set D1_D2
Test model on ADNI data set D2 rollover participants
"""

# Load D1_D2 train and possible test data set
data_path_train_test = Path("data/TADPOLE_D1_D2.csv")
data_df_train_test = pd.read_csv(data_path_train_test)

# Load D4 evaluation data set 
data_path_eval = Path("data/TADPOLE_D4_corr.csv")
data_df_eval = pd.read_csv(data_path_eval)

# Split data in test, train and evaluation data
train_df, test_df, eval_df = split_test_train_tadpole(data_df_train_test, data_df_eval)
test_df = test_df.fillna(0)

# Define and train model
model = BenchmarkLastVisit()
model.train(train_df)

# Predict forecast on the test set
forecast_df_d2 = model.predict(test_df)

In [5]:
train_df

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,...,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,2005-09-08,CN,...,,,,,,,,,,
22,8,011_S_0008,bl,11,1,1,ADNI1,ADNI1,2005-09-19,CN,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,2017-01-06,3592,440.2,37.51,Recalculated ABETA result = 3592 pg/mL,2017-04-20 14:39:54.0
23,8,011_S_0008,m06,11,1,1,ADNI1,ADNI1,2006-03-20,CN,...,,,,,,,,,,
33,15,100_S_0015,bl,100,1,1,ADNI1,ADNI1,2005-10-18,CN,...,,,,,,,,,,
34,15,100_S_0015,m12,100,1,1,ADNI1,ADNI1,2006-10-13,CN,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12736,4167,116_S_4167,m60,116,1,1,ADNI2,ADNI2,2016-11-16,LMCI,...,,,,,,,,,,
12737,4199,116_S_4199,m60,116,1,1,ADNI2,ADNI2,2016-12-12,EMCI,...,,,,,,,,,,
12738,4557,053_S_4557,m60,53,1,1,ADNI2,ADNI2,2017-03-15,EMCI,...,,,,,,,,,,
12739,4512,100_S_4512,m48,100,1,1,ADNI2,ADNI2,2017-04-04,EMCI,...,,,,,,,,,,
12740,2380,036_S_2380,m72,36,1,1,ADNI2,ADNIGO,2017-05-05,EMCI,...,,,,,,,,,,

Train model on data set D1_D2 and test model on cross sectional data set D3

In [6]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import BenchmarkLastVisit
from tadpole_algorithms.preprocessing.split import split_test_train_d3
from tadpole_algorithms.preprocessing.rewrite_df import rewrite_d3

"""
Train model on ADNI data set D1_D2
Test model on ADNI data set D3 rollover participants
"""

# Load D1_D2 train and possible test data set
data_path_train = Path("data/TADPOLE_D1_D2.csv")
data_df_train = pd.read_csv(data_path_train)

# Load D3 possible test set
data_path_test = Path("data/TADPOLE_D3.csv")
data_df_test = pd.read_csv(data_path_test)

# Load D4 evaluation data set
data_path_eval = Path("data/TADPOLE_D4_corr.csv")
data_df_eval = pd.read_csv(data_path_eval)

# Split data in test, train and evulation data
train_df, test_df, eval_df = split_test_train_d3(data_df_train, data_df_test, data_df_eval)
test_df = test_df.fillna(0)
test_df = rewrite_d3(test_df)

# Define and train model
model = BenchmarkLastVisit()
model.train(train_df)

# Predict forecast on the test set
forecast_df_d3 = model.predict(test_df)

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,745,746,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,770,771,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,794,795,797,798,799,800,801,802,803,804,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/Eider/GitHub/R_Python_interoperability/tadpole_algorithms/models/benchmark_last_visit/__init__.py:47: RuntimeWarning: invalid value encountered in true_divide
  train_df["Ventricles_ICV"] = train_df["Ventricles"].values / train_df["ICV_bl"].values

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

In [8]:
type(forecast_df_d3)

pandas.core.frame.DataFrame

Evaluate model tested on D2 on ADNI data set D4

In [4]:
from tadpole_algorithms.evaluation import evaluate_forecast
from tadpole_algorithms.evaluation import print_metrics

# Evaluate the model 
dictionary = evaluate_forecast(eval_df, forecast_df_d2)

# Print metrics
print_metrics(dictionary)

[[68  9  9]
 [16 61 15]
 [ 2 12 18]]
mAUC (multiclass Area Under Curve): 0.7408406332329271
bca (balanced classification accuracy): 0.7833531004763881
adasMAE (ADAS13 Mean Aboslute Error): 6.9877168949771695
ventsMAE (Ventricles Mean Aboslute Error): 20166.64347547878
adasWES (ADAS13 Weighted Error Score): 7.092919047619048
ventsWES (Ventricles Weighted Error Score ): 4315.262894732479
adasCPA (ADAS13 Coverage Probability Accuracy for 50% Confidence Interval: 0.4178082191780822
ventsCPA (Ventricles Coverage Probability Accuracy for 50% Confidence Interval: 0.30666666666666664

In [ ]:
Evaluate model tested on D3 on ADNI data set D4

In [4]:
from tadpole_algorithms.evaluation import evaluate_forecast
from tadpole_algorithms.evaluation import print_metrics

# Evaluate the model 
dictionary = evaluate_forecast(eval_df, forecast_df_d3)

# Print metrics
print_metrics(dictionary)

[[69  8  9]
 [16 64 12]
 [ 2 12 18]]
mAUC (multiclass Area Under Curve): 0.753
bca (balanced classification accuracy): 0.771
adasMAE (ADAS13 Mean Aboslute Error): 6.969
ventsMAE (Ventricles Mean Aboslute Error): 0.012
adasWES (ADAS13 Weighted Error Score): 7.066
ventsWES (Ventricles Weighted Error Score ): 0.006
adasCPA (ADAS13 Coverage Probability Accuracy for 50% Confidence Interval: 0.422
ventsCPA (Ventricles Coverage Probability Accuracy for 50% Confidence Interval: 0.020